### ISSUE TITLE
请教您一个问题

### ISSUE THREAD

**Issue by FrankCYQ** [ModulizationDemo/ModulizedMainProject#1]
是不是A中AViewcontroller调用B_category 就不能再Bviewcontroller中再调用了A_category,否则就编译不通过，我目前就遇到这样的问题了

**Comment by casatwy** [comment]
不会的，我的demo也在b中调用a category了。你看一下你category的podspec有没有把组件写进去？不应该写的

**Comment by FrankCYQ** [comment]
您demo中的B的实现（taget/action）是在主工程中，那种调用时没有问题的，我现在是完全把b的业务拆分出来了，和category一致都是私有库，然后b的业务实现调用了a的category，a的实现也调用了B
的category就出问题了，在主工程中同事引用了a、b的实现库，就编译不通过，单独使用都没有问题

**Comment by casatwy** [comment]
是因为符号重名了

发自我的 iPhone

在 2017年5月27日，上午9:51，Frank <notifications@github.com<mailto:notifications@github.com>> 写道：


您demo中的B的实现（taget/action）是在主工程中，那种调用时没有问题的，我现在是完全把b的业务拆分出来了，和category一致都是私有库，然后b的业务实现调用了a的category，a的实现也调用了B
的category就出问题了，在主工程中同事引用了a、b的实现库，就编译不通过，单独使用都没有问题

**Comment by FrankCYQ** [comment]
谢谢大神，问题已经解决啦，主要是我业务a、b中类名重复以及对应category 宏定义重复了，和组件化开发没有关系。主要是自己对cocoapods使用太少

**Comment by casatwy** [comment]
OK
