### ISSUE TITLE
Category的划分问题

### ISSUE THREAD

**Issue by w-qihang** [ModulizationDemo/ModulizedMainProject#2]
将所有的category 放在一个仓库，提供给上层业务调用是否是一种好的选择？是否影响了架构设计?

**Comment by casatwy** [comment]
不影响架构设计，但不是一种好的选择。

因为：

1. category这个pod是由响应者的pod开发者维护的，全放一起会提高维护成本。

2. 全放一起会提高迁移和复用的成本。如果你们公司有多个app，它们都使用了某个响应者的功能，全放一起就很蛋疼。
